"""Recreate initial migration

Revision ID: 505e433cfec3
Revises: cb236b8339a7
Create Date: 2024-09-08 19:35:13.637691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505e433cfec3'
down_revision = 'cb236b8339a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('colors', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('desc', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('image_1', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('image_2', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('image_3', sa.String(length=150), nullable=False))
        
        # Add the foreign key constraint with a name
        batch_op.create_foreign_key(
            'fk_addproduct_brand_id',  # Constraint name
            'brand',
            ['brand_id'],
            ['id']
        )
        
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))
        
        # Drop the foreign key constraint by its name
        batch_op.drop_constraint('fk_addproduct_brand_id', type_='foreignkey')
        
        batch_op.drop_column('image_3')
        batch_op.drop_column('image_2')
        batch_op.drop_column('image_1')
        batch_op.drop_column('brand_id')
        batch_op.drop_column('desc')
        batch_op.drop_column('colors')
        batch_op.drop_column('stock')
        batch_op.drop_column('discount')
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
